# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directories

version: 2

updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 30
    directory: "/"
    labels:
      - " Dependencies"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    open-pull-requests-limit: 30
    directories:
      - "**/*"
    labels:
      - " Dependencies"
    schedule:
      interval: "daily"
    groups:
      fiber-modules:
        patterns:
          - "github.com/gofiber/fiber/**"
      fasthttp-modules:
        patterns:
          - "github.com/valyala/fasthttp"
          - "github.com/valyala/fasthttp/**"
      golang-modules:
        patterns:
          - "golang.org/x/**"
      gorm-modules:
        patterns:
          - "gorm.io/**"
      postgres-modules:
        patterns:
          - "github.com/jackc/pgx/**"
          - "github.com/lib/pq"
      mysql-modules:
        patterns:
          - "github.com/go-sql-driver/mysql"
      mongodb-modules:
        patterns:
          - "go.mongodb.org/**"
      redis-modules:
        patterns:
          - "github.com/go-redis/**"
      jwt-modules:
        patterns:
          - "github.com/golang-jwt/jwt/**"
          - "github.com/gofiber/contrib/jwt"
      entgo-modules:
        patterns:
          - "entgo.io/**"
      google-cloud-modules:
        patterns:
          - "cloud.google.com/**"
          - "firebase.google.com/**"
      aws-modules:
        patterns:
          - "github.com/aws/**"
  - package-ecosystem: "npm"
    open-pull-requests-limit: 15
    directories:
      - "**/*"
    labels:
      - " Dependencies"
    schedule:
      interval: "daily"
    groups:
      svelte-modules:
        patterns:
          - "svelte"
          - "@sveltejs/**"
      tailwind-modules:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
      typescript-modules:
        patterns:
          - "typescript"
          - "tslib"
          - "@typescript-eslint/*"
      react-modules:
        patterns:
          - "react"
          - "react-dom"
          - "react-router-dom"
          - "react-scripts"
          - "@types/react*"
          - "@testing-library/*"
  - package-ecosystem: "docker"
    open-pull-requests-limit: 15
    directories:
      - "**/*"
    labels:
      - " Dependencies"
    schedule:
      interval: "daily"
