# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directories

version: 2

updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 60
    directory: "/"
    labels:
      - " Dependencies"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    open-pull-requests-limit: 60
    allow:
      # Allow both direct and indirect updates for all packages.
      - dependency-type: "all"
    directories:
      - "**/*"
    labels:
      - " Dependencies"
    schedule:
      interval: "daily"
    groups:
      fiber-modules:
        patterns:
          - "github.com/gofiber/fiber/**"
      fasthttp-modules:
        patterns:
          - "github.com/valyala/fasthttp"
          - "github.com/valyala/fasthttp/**"
      golang-modules:
        patterns:
          - "golang.org/x/**"
      gorm-modules:
        patterns:
          - "gorm.io/**"
      postgres-modules:
        patterns:
          - "github.com/jackc/pgx/**"
          - "github.com/lib/pq"
      mysql-modules:
        patterns:
          - "github.com/go-sql-driver/mysql"
      mongodb-modules:
        patterns:
          - "go.mongodb.org/**"
      redis-modules:
        patterns:
          - "github.com/go-redis/**"
      jwt-modules:
        patterns:
          - "github.com/golang-jwt/jwt/**"
          - "github.com/gofiber/contrib/jwt"
      entgo-modules:
        patterns:
          - "entgo.io/**"
      google-cloud-modules:
        patterns:
          - "cloud.google.com/**"
          - "firebase.google.com/**"
      aws-modules:
        patterns:
          - "github.com/aws/**"
      grpc-modules:
        patterns:
          - "google.golang.org/grpc"
          - "google.golang.org/grpc/**"
      opentelemetry-modules:
        patterns:
          - "go.opentelemetry.io/**"
          - "github.com/GoogleCloudPlatform/opentelemetry-operations-go/**"
      logging-modules:
        patterns:
          - "go.uber.org/zap/**"
          - "github.com/sirupsen/logrus"
          - "github.com/sirupsen/logrus/**"
      mattn-modules:
        patterns:
          - "github.com/mattn/go-sqlite*"
      spf13-modules:
        patterns:
          - "github.com/spf13/**"
      gorilla-modules:
        patterns:
          - "github.com/gorilla/**"
      validator-modules:
        patterns:
          - "github.com/go-playground/validator"
          - "github.com/go-playground/validator/**"
      testcontainers-modules:
        patterns:
          - "github.com/testcontainers/**"
      testing-modules:
        patterns:
          - "github.com/stretchr/**"
          - "github.com/golang/mock/**"
  - package-ecosystem: "npm"
    open-pull-requests-limit: 15
    directories:
      - "**/*"
    labels:
      - " Dependencies"
    schedule:
      interval: "daily"
    groups:
      svelte-modules:
        patterns:
          - "svelte"
          - "@sveltejs/**"
      tailwind-modules:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
      typescript-modules:
        patterns:
          - "typescript"
          - "tslib"
          - "@typescript-eslint/*"
      react-modules:
        patterns:
          - "react"
          - "react-dom"
          - "react-router-dom"
          - "react-scripts"
          - "@types/react*"
          - "@testing-library/*"
      eslint-modules:
        patterns:
          - "eslint"
          - "eslint-*"
          - "eslint-plugin*"
          - "eslint-config*"
      prettier-modules:
        patterns:
          - "prettier"
          - "prettier-*"
      bundler-modules:
        patterns:
          - "vite"
          - "parcel"
  - package-ecosystem: "docker"
    open-pull-requests-limit: 15
    directories:
      - "**/*"
    labels:
      - " Dependencies"
    schedule:
      interval: "daily"
